spring:
  application:
    name: ConflictTracker

  profiles:
    active: dev  # "dev" para desarrollo con H2 "prod" para producci�n con PostgreSQL

  # Configuraci�n com�n para JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuraci�n com�n para servidor
  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080

# Logging com�n
logging:
  level:
    com.example.conflicttracker: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE