spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:conflictdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop  # Para desarrollo, recrea la BD cada vez
    defer-datasource-initialization: true  # Importante para data.sql

  sql:
    init:
      mode: always  # Siempre ejecutar data.sql
      encoding: UTF-8

  h2:
    console:
      enabled: true
      path: /h2-console  # http://localhost:8080/h2-console