spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/conflicttracker
    username: postgres
    password: CONTRASEÑA  # Cambia esto
    driver-class-name: org.postgresql.Driver

  jpa:
    # database-platform: org.hibernate.dialect.PostgreSQLDialect  # Opcional, Spring lo detecta
    hibernate:
      ddl-auto: update  # Para producción, actualiza sin borrar datos
    defer-datasource-initialization: true

  sql:
    init:
      mode: always  # O 'never' si no quieres data.sql en producción
      encoding: UTF-8

  h2:
    console:
      enabled: false  # Deshabilitar H2 en producción